[tool.isort]
profile = "black"  # Совместимость с black
line_length = 88
known_third_party = [
    "Pyrogram",
    "TgCrypto",
    "SQLAlchemy",
    "Alembic",
    "redis",
    "dotenv",
    "aiofiles",
    "asyncpg",
]

known_first_party = ["bot", "db", "redis_db"]

[tool.black]
line-length = 140  # Для вас это может быть иначе. Но у меня несколько мониторов и я могу читать длинный код
target-version = ['py310']
skip-string-normalization = false


[tool.mypy]
python_version = "3.10"
strict = true
ignore_missing_imports = true
disallow_untyped_calls = true
disallow_untyped_defs = true
warn_return_any = true
warn_unused_ignores = true
#explicit-package-bases = true
exclude = "(__pycache__|venv|temp|.env|logs|db/migrations|db/env.py)"

[tool.autoflake]
remove-all-unused-imports = true
in-place = true
recursive = true
exclude = ["venv", "db/migrations", "temp", "logs"]
